/**
 * Parsed training centers data from ULC PDFs
 */

export const TRAINING_CENTERS_DATA = [
  // ATO/CTO from first PDF
  {
    name: 'ACSL LOTNICZEJ AKADEMII WOJSKOWEJ',
    type: 'ATO' as const,
    certificateNumber: 'PL.ATO.00108-521',
    address: 'ul. Dywizjonu 303 nr 35',
    city: 'Dęblin',
    phone: '(81) 551 94 27',
    fax: '(81) 551 94 27',
    email: 'zsergiel@wp.pl',
    trainingCourses: [
      { code: 'PPL(A)', name: 'Pilot turystyczny samolotowy', theory: true, practical: true },
      { code: 'FNPT II', name: 'Symulator', theory: false, practical: true, simulator: 'PL-17-01' },
      { code: 'PPL(H)', name: 'Pilot turystyczny śmigłowcowy', theory: true, practical: true },
      { code: 'CPL(A)', name: 'Pilot zawodowy samolotowy', theory: true, practical: true },
      { code: 'CPL(H)', name: 'Pilot zawodowy śmigłowcowy', theory: true, practical: true },
      { code: 'ATPL(A)', name: 'Pilot liniowy samolotowy', theory: true, practical: true },
      { code: 'MEP(L)', name: 'Samoloty wielosilnikowe tłokowe lądowe', theory: true, practical: true },
      { code: 'FI(A)', name: 'Instruktor samolotowy', theory: true, practical: true },
      { code: 'FI(H)', name: 'Instruktor szkolenia śmigłowcowego', theory: true, practical: true },
      { code: 'IR/SE', name: 'Uprawnienie do lotów wg wskazań przyrządów/jednosilnikowe', theory: true, practical: true },
      { code: 'IR/ME', name: 'Uprawnienie do lotów wg wskazań przyrządów/wielosilnikowe', theory: true, practical: true },
      { code: 'IRI', name: 'Uprawnienie instruktora szkolenia w lotach według wskazań przyrządów', theory: true, practical: true },
      { code: 'CRI/ME', name: 'Uprawnienie instruktora na klasę samolotów wielosilnikowych', theory: true, practical: true },
      { code: 'TR', name: 'Type Rating - Cabri G2, R-44', theory: true, practical: true },
      { code: 'SEP (L)', name: 'Inny typ w klasie SEP(L)', theory: true, practical: true },
      { code: 'MEP (L)', name: 'Inny typ w klasie MEP(L)', theory: true, practical: true },
      { code: 'night (A)', name: 'uprawnienie samolotowe do wyk. lotów nocnych', theory: true, practical: true },
      { code: 'night (H)', name: 'uprawnienie śmigłowcowe do wyk. lotów nocnych', theory: true, practical: true },
      { code: 'STI(A)', name: 'Instruktor szkolenia na urządzeniach syntetycznych', theory: true, practical: true },
      { code: 'aerobatics A', name: 'uprawnienia do wykonywania akrobacji (samoloty)', theory: true, practical: true },
      { code: 'banner towing', name: 'uprawnienia do holowania banerów', theory: true, practical: true },
    ],
  },
  {
    name: 'TECHNIKA /AEROTECHNIKA',
    type: 'ATO' as const,
    certificateNumber: 'PL.ATO.00261-315',
    address: 'ul. Pokrzywno 8',
    city: 'Poznań',
    phone: '(61) 879 82 50',
    fax: '(61) 879 89 33',
    email: 'office@domicz.com.pl',
    trainingCourses: [
      { code: 'PPL(A)', name: 'Pilot turystyczny samolotowy', theory: true, practical: true },
      { code: 'CPL(A)', name: 'Pilot zawodowy samolotowy', theory: true, practical: true },
      { code: 'LAPL(A)', name: 'Pilot samolotowy rekreacyjny', theory: true, practical: true },
      { code: 'IR(A)', name: 'Uprawnienie do lotów według wskazań przyrządów- samoloty', theory: true, practical: true },
      { code: 'IRI', name: 'Uprawnienie instruktora szkolenia w lotach według wskazań przyrządów', theory: true, practical: true },
      { code: 'CRI(A)', name: 'Instruktor szkolenia na klasę', theory: true, practical: true },
      { code: 'MEP(L)', name: 'Samoloty wielosilnikowe tłokowe lądowe', theory: true, practical: true },
      { code: 'night (A)', name: 'uprawnienie samolotowe do wyk. lotów nocnych', theory: true, practical: true },
      { code: 'FI(A)', name: 'Instruktor samolotowy', theory: true, practical: true },
    ],
  },
  {
    name: 'OKL POLITECHNIKI RZESZOWSKA',
    type: 'ATO' as const,
    certificateNumber: 'PL.ATO.00336-001',
    address: 'Jasionka 915',
    city: 'Trzebownisko',
    phone: '(17) 771 33 00',
    fax: '(17) 772 21 20',
    email: 'oklprz@prz.edu.pl',
    trainingCourses: [
      { code: 'PPL(A)', name: 'Pilot turystyczny samolotowy', theory: true, practical: true },
      { code: 'CPL(A)', name: 'Pilot zawodowy samolotowy', theory: true, practical: true },
      { code: 'ATPL(A)', name: 'Pilot liniowy samolotowy', theory: true, practical: true },
      { code: 'FI(A)', name: 'Instruktor samolotowy', theory: true, practical: true },
      { code: 'IR(A)', name: 'Uprawnienie do lotów według wskazań przyrządów- samoloty', theory: true, practical: true },
      { code: 'IRI', name: 'Uprawnienie instruktora szkolenia w lotach według wskazań przyrządów', theory: true, practical: true },
      { code: 'MCC(A)', name: 'Szkolenie w zakresie współpracy w załodze wieloosobowej', theory: true, practical: true },
      { code: 'MCCI(A)', name: 'Uprawnienia instruktora do szkolenie w zakresie współpracy w załodze', theory: true, practical: true },
      { code: 'CRI/ME', name: 'Uprawnienie instruktora na klasę samolotów wielosilnikowych', theory: true, practical: true },
      { code: 'MEP(L)', name: 'Samoloty wielosilnikowe tłokowe lądowe', theory: true, practical: true },
      { code: 'night (A)', name: 'uprawnienie samolotowe do wyk. lotów nocnych', theory: true, practical: true },
      { code: 'aerobatics A', name: 'uprawnienia do wykonywania akrobacji (samoloty)', theory: true, practical: true },
    ],
  },
  {
    name: 'DIRECT DISPATCH',
    type: 'CTO' as const,
    certificateNumber: 'PL.CTO.00402-822',
    address: 'ul. Poleczki 23',
    city: 'Warszawa',
    phone: '+48 (22) 462 40 11; 270 26 85',
    email: 'training@dct.aero',
    trainingCourses: [
      { code: 'FDL', name: 'Licencja dyspozytora lotniczego', theory: true, practical: false },
    ],
  },
  {
    name: '"NORMAL" PIOTR JAFERNIK',
    type: 'ATO' as const,
    certificateNumber: 'PL.ATO.00543-300',
    address: 'ul. Cieszyńska 319',
    city: 'Bielsko-Biała',
    phone: '(33) 811 37 50',
    fax: '(33) 815 77 73',
    email: 'biuro@normal-jafernik.com.pl',
    trainingCourses: [
      { code: 'PPL(A)', name: 'Pilot turystyczny samolotowy', theory: true, practical: true },
      { code: 'PPL(H)', name: 'Pilot turystyczny śmigłowcowy', theory: true, practical: true },
      { code: 'CPL(A)', name: 'Pilot zawodowy samolotowy', theory: true, practical: true },
      { code: 'CPL(H)', name: 'Pilot zawodowy śmigłowcowy', theory: true, practical: true },
      { code: 'night (A)', name: 'uprawnienie samolotowe do wyk. lotów nocnych', theory: true, practical: true },
      { code: 'night (H)', name: 'uprawnienie śmigłowcowe do wyk. lotów nocnych', theory: true, practical: true },
      { code: 'SETP(L)', name: 'Samoloty jednosilnikowe turbośmigłowe lądowe: Cessna SET', theory: true, practical: true },
      { code: 'TR', name: 'Type Rating - ENF 28, EC120, AS350/EC130, BELL206/206L', theory: true, practical: true },
      { code: 'CRI SC7', name: 'SC-7 SKYVAN', theory: true, practical: true },
      { code: 'CRI Cessna SET', name: 'Cessna SET', theory: true, practical: true },
    ],
  },
  {
    name: 'IBEX - U.L. SP. Z O.O.',
    type: 'ATO' as const,
    certificateNumber: 'PL.ATO.00601-248',
    address: 'ul. Jana Kazimierza 11 lok. 4',
    city: 'Warszawa',
    phone: '(22) 620 40 31',
    fax: '(22) 652 34 02',
    email: 'szkolenie@ibex.aero',
    trainingCourses: [
      { code: 'PPL(A)', name: 'Pilot turystyczny samolotowy', theory: true, practical: true },
      { code: 'LAPL(A)', name: 'Pilot samolotowy rekreacyjny', theory: true, practical: true },
      { code: 'PPL(H)', name: 'Pilot turystyczny śmigłowcowy', theory: true, practical: true },
      { code: 'CPL(A)', name: 'Pilot zawodowy samolotowy', theory: true, practical: true },
      { code: 'ATPL(A)', name: 'Pilot liniowy samolotowy', theory: true, practical: true },
      { code: 'ATPL(H)', name: 'Pilot liniowy śmigłowcowy', theory: true, practical: true },
      { code: 'UPRT', name: 'Szkolenie zaawansowane UPRT (FCL 745A)', theory: true, practical: true },
      { code: 'IR/SE', name: 'Uprawnienie do lotów wg wskazań przyrządów/jednosilnikowe', theory: true, practical: true },
      { code: 'IR/ME', name: 'Uprawnienie do lotów wg wskazań przyrządów/wielosilnikowe', theory: true, practical: true },
      { code: 'night (A)', name: 'uprawnienie samolotowe do wyk. lotów nocnych', theory: true, practical: true },
      { code: 'night (H)', name: 'uprawnienie śmigłowcowe do wyk. lotów nocnych', theory: true, practical: true },
      { code: 'FI(A)', name: 'Instruktor samolotowy', theory: true, practical: true },
      { code: 'FI(H)', name: 'Instruktor szkolenia śmigłowcowego', theory: true, practical: true },
      { code: 'MEP(L)', name: 'Samoloty wielosilnikowe tłokowe lądowe', theory: true, practical: true },
    ],
  },
  {
    name: 'CTO PILEUS',
    type: 'CTO' as const,
    certificateNumber: 'PL.CTO.00705-807',
    address: 'ul. Brzozowa 11',
    city: 'Podkowa Leśna',
    phone: '(22) 393 11 40',
    fax: '(22) 393 11 41',
    email: 'szkolenia@pileus.eu',
    trainingCourses: [
      { code: 'FDL', name: 'Licencja dyspozytora lotniczego', theory: true, practical: false },
    ],
  },
  // Continue with more centers... (this is a sample)
];

export const DTO_DATA = [
  {
    name: 'Szybowcowy Szczecin',
    type: 'DTO' as const,
    certificateNumber: 'PL.DTO-1',
    address: 'ul. Chmielewskiego 22a',
    city: '70-028 Szczecin',
    phone: '+48 666 079 624',
    email: 'szybowcowy.szczecin@gmail.com',
    trainingCourses: [
      { code: 'SPL', name: 'Szkolenie teoretyczne i praktyczne do SPL' },
      { code: 'FI(S)', name: 'Szkolenie na dodatkowe uprawnienia instruktora szkolenia praktycznego FI(S)' },
      { code: 'aerobatics S', name: 'uprawnienie dodatkowe: podstawowe i zaawansowane uprawnienia akrobacyjne na szybowcach' },
      { code: 'towing gliders', name: 'uprawnienie do holowania szybowców' },
      { code: 'PPL(A)', name: 'Szkolenie teoretyczne i praktyczne do LAPL(A) i PPL(A)' },
      { code: 'SEP(L)', name: 'Szkolenie na uprawnienie na klasę SEP(lądowych) i TMG' },
      { code: 'night (A)', name: 'Szkolenie samolotowe do uprawnienia dodatkowego: do wykonywania lotów nocnych' },
    ],
  },
  {
    name: 'Firebirds Flight Academy Sp. z o.o.',
    type: 'DTO' as const,
    certificateNumber: 'PL.DTO-2',
    address: 'ul. Lotnisko Muchowiec',
    city: '40-271 Katowice',
    phone: '',
    email: 'marcel.kotas@gmail.com',
    trainingCourses: [
      { code: 'aerobatics A', name: 'Szkolenie do uprawnienia dodatkowego: akrobacja na samolotach' },
    ],
  },
  {
    name: 'Aeroklub Ziemi Jarosławskiej',
    type: 'DTO' as const,
    certificateNumber: 'PL.DTO-3',
    address: 'Lądowisko Laszki',
    city: '37-543 Laszki',
    phone: '+48 79 374 47 84',
    email: 'biuro@aeroklubjaroslaw.pl',
    trainingCourses: [
      { code: 'SPL', name: 'Szkolenie teoretyczne i praktyczne do SPL' },
    ],
  },
  // Continue with more DTOs... (this is a sample)
];